name: Code checks CI

on:
  pull_request:
    branches:
      - main
      - 'release/**'
      - develop

jobs:

  test:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Testing with Maven
        run: mvn -B test --file pom.xml

      - name: Verify Code Style & PMD rules with Maven
        run: mvn -B verify --file pom.xml